const https = require('https');

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_OWNER = process.env.GITHUB_OWNER;
const GITHUB_REPO = process.env.GITHUB_REPO;

/**
 * Make GitHub API request
 */
function githubRequest(method, path, data = null) {
  return new Promise((resolve, reject) => {
    const options = {
      hostname: 'api.github.com',
      port: 443,
      path,
      method,
      headers: {
        'Authorization': `token ${GITHUB_TOKEN}`,
        'User-Agent': 'Dev-Agent',
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json'
      }
    };

    const req = https.request(options, (res) => {
      let body = '';

      res.on('data', (chunk) => {
        body += chunk;
      });

      res.on('end', () => {
        if (res.statusCode >= 200 && res.statusCode < 300) {
          resolve(JSON.parse(body || '{}'));
        } else {
          reject(new Error(`GitHub API error: ${res.statusCode} - ${body}`));
        }
      });
    });

    req.on('error', reject);

    if (data) {
      req.write(JSON.stringify(data));
    }

    req.end();
  });
}

/**
 * Create a pull request
 */
async function createPullRequest(prMetadata) {
  const { title, description, branch, changes_summary, testing_notes } = prMetadata;

  // Format description with changes
  let body = description + '\n\n## Changes\n';
  changes_summary.forEach(change => {
    body += `- ${change}\n`;
  });

  if (testing_notes) {
    body += `\n## Testing\n${testing_notes}\n`;
  }

  body += '\n---\n*Generated by Dev Agent*';

  const data = {
    title,
    body,
    head: branch,
    base: 'main' // or 'master'
  };

  try {
    const result = await githubRequest(
      'POST',
      `/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls`,
      data
    );

    console.log(`✓ Pull request created: ${result.html_url}`);
    return result;
  } catch (error) {
    // Try with 'master' as base if 'main' fails
    if (error.message.includes('404')) {
      data.base = 'master';
      const result = await githubRequest(
        'POST',
        `/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls`,
        data
      );
      console.log(`✓ Pull request created: ${result.html_url}`);
      return result;
    }
    throw error;
  }
}

/**
 * Get repository info
 */
async function getRepoInfo() {
  return githubRequest('GET', `/repos/${GITHUB_OWNER}/${GITHUB_REPO}`);
}

/**
 * List open pull requests
 */
async function listPullRequests(state = 'open') {
  return githubRequest('GET', `/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls?state=${state}`);
}

module.exports = {
  createPullRequest,
  getRepoInfo,
  listPullRequests
};